### ISSUE TITLE
def sign_message

### ISSUE THREAD

**Issue by crypto-chen** [FrankC01/pysui-fastcrypto#8]
thread '<unnamed>' panicked at src\lib.rs:500:40:
called `Result::unwrap()` on an `Err` value: Error decoding aaa
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "F:\python240416\re_socl\galxe\草稿.py", line 43, in <module>
    signature = keypair.sign_message('aaa')
  File "E:\Python310\lib\site-packages\pysui\sui\sui_crypto.py", line 125, in sign_message
    return pfc.sign_message(self.scheme, self.private_key.key_bytes, message)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Error decoding aaa

**Comment by crypto-chen** [comment]
keypair = SuiKeyPair()
keypair._private_key = SuiPrivateKey(key_bytes=private_key_bytes, scheme=SignatureScheme.ED25519)

signature = keypair.sign_message('aaa')
print(f"sign: {signature}")

**Comment by crypto-chen** [comment]
Why did it go wrong?

**Comment by FrankC01** [comment]
"aaa" is not a valid base64 encoded string
```python
>>> base64.b64decode("aaa")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
```

"aaaa" is

**Comment by crypto-chen** [comment]
def sign_message(self, message: str) -> str:
        """Sign arbitrary message, returning it's base64 raw signature."""
        return pfc.sign_message(self.scheme, self.private_key.key_bytes, message)

**Comment by crypto-chen** [comment]
Pass in str? But not base64?

**Comment by crypto-chen** [comment]
Is that so?`# 原始字符串
original_string = "aaa"

# 转换为字节
bytes_string = original_string.encode('utf-8')

# 转换为 Base64
base64_string = base64.b64encode(bytes_string).decode('utf-8')
signature = keypair.sign_message(base64_string)
print(f"sign: {signature}")`

**Comment by FrankC01** [comment]
Your example had `aaa` as the input string to the function which is not a properly aligned base64 str
